### PR TITLE
xyzcoder task

### PR DESCRIPTION
**Pull request by xyzcoderFD**

### CODE REVIEW

**Comment by nelsonmic** [comment]
The number input field should be left just like that, only the inputs with id's of FROM and TO shou;ld be changed to select input type. please review the changes and make corrections, then I'll merge

**Review by nelsonmic — CHANGES_REQUESTED** [review]
The first select field should be put under the the div with a class of left and the other one should be under the div Class of left and change their id selector to what it was before which is "from" and "to" .... please revert the styles

**Comment by xyzcoderFD** [comment]
i have rectify it already u can merge now

**Review by nelsonmic — APPROVED** [review]
Awesome work sir

**Pull request merged**
